### ISSUE TITLE
Process fails when input file contains spaces

### ISSUE THREAD

**Issue by mmendelson222** [aws-samples/amazon-textract-enhancer#1]
Lambda TextractAsyncJobSubmitFunction runs to success, but actually fails to process the file.  The following errors can be seen in CloudWatch:

- An error occurred (InvalidParameterException) when calling the StartDocumentAnalysis operation: Request has invalid parameters
- An error occurred (InvalidParameterException) when calling the StartDocumentTextDetection operation: Request has invalid parameters

Two issues: 1. the problem specified above, and 2. the Lambda itself should probably fail under these circumstances (can't perform operation after retries). 

Thanks for this code.

**Comment by dbinoy** [comment]
Thanks for bringing this to attention. The code in job submission Lambda now checks for invalid parameter exception, and fails gracefully with failure message captured in Log and returned to invocation source.

**Comment by matwerber1** [comment]
I don't think spaces are the root cause; it has to do with the fact that the S3 event is URL encoding the S3 key name and the Lambda isn't decoding it before passing to Textract. I opened issue #2 with PR #3 to decode the key name which should allow spaces to be used.
